-- Classifieds Categories
create table if not exists classified_categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  icon text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Classified Ads
create table if not exists classified_ads (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  price numeric,
  price_unit text, -- 'item', 'hour', 'day'
  ad_type text, -- 'sale', 'rent', 'service'
  category_id bigint references classified_categories(id) on delete set null,
  user_id uuid references profiles(id) on delete cascade,
  image_url text,
  status text default 'active', -- 'active', 'sold', 'deleted'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Chats
create table if not exists chats (
  id bigint generated by default as identity primary key,
  ad_id bigint references classified_ads(id) on delete set null,
  buyer_id uuid references profiles(id) on delete cascade,
  seller_id uuid references profiles(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(ad_id, buyer_id) -- One chat per buyer per ad
);

-- Messages
create table if not exists messages (
  id bigint generated by default as identity primary key,
  chat_id bigint references chats(id) on delete cascade,
  sender_id uuid references profiles(id) on delete cascade,
  content text not null,
  read_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table classified_categories enable row level security;
alter table classified_ads enable row level security;
alter table chats enable row level security;
alter table messages enable row level security;

-- Policies

-- Categories: Public read
create policy "Public classified categories are viewable by everyone" on classified_categories for select using (true);

-- Ads: Public read (active only usually, but for now all), Owner write
create policy "Public ads are viewable by everyone" on classified_ads for select using (true);
create policy "Users can insert their own ads" on classified_ads for insert with check (auth.uid() = user_id);
create policy "Users can update their own ads" on classified_ads for update using (auth.uid() = user_id);
create policy "Users can delete their own ads" on classified_ads for delete using (auth.uid() = user_id);

-- Chats: Participants read/write
create policy "Users can view their own chats" on chats for select using (auth.uid() = buyer_id or auth.uid() = seller_id);
create policy "Users can create chats" on chats for insert with check (auth.uid() = buyer_id);

-- Messages: Participants read, Sender write
create policy "Users can view messages in their chats" on messages for select using (
  exists (
    select 1 from chats
    where chats.id = messages.chat_id
    and (chats.buyer_id = auth.uid() or chats.seller_id = auth.uid())
  )
);
create policy "Users can send messages to their chats" on messages for insert with check (
  exists (
    select 1 from chats
    where chats.id = messages.chat_id
    and (chats.buyer_id = auth.uid() or chats.seller_id = auth.uid())
  )
);

-- Insert Sample Categories
insert into classified_categories (name, slug, icon) values
('Electronics', 'electronics', '💻'),
('Vehicles', 'vehicles', '🚗'),
('Furniture', 'furniture', '🪑'),
('Services', 'services', '🛠️'),
('Real Estate', 'real-estate', '🏠'),
('Fashion', 'fashion', '👕')
on conflict (slug) do nothing;
