-- Create Date Plans Table
create table if not exists date_plans (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  title text not null default 'The Evening Plan',
  stops jsonb not null default '[]'::jsonb,
  stickers jsonb not null default '[]'::jsonb,
  is_public boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table date_plans enable row level security;

-- Policies
create policy "Public date plans are viewable by everyone" 
  on date_plans for select 
  using (is_public = true or auth.uid() = user_id);

create policy "Users can insert their own date plans" 
  on date_plans for insert 
  with check (auth.uid() = user_id);

create policy "Users can update their own date plans" 
  on date_plans for update 
  using (auth.uid() = user_id);

create policy "Users can delete their own date plans" 
  on date_plans for delete 
  using (auth.uid() = user_id);
